server:
  port: 8111

spring:
  datasource:
    dynamic:
      primary: master
      strict: true
      printQuery: true
      druid:
        initialSize: 10
        maxActive: 20
        minIdle: 10
        maxWait: 5000
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:${MYSQL-PORT:3307}/${MYSQL-DB:ele}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
          username: root
          password: 12345678
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://127.0.0.1:${MYSQL-PORT:3307}/${MYSQL-DB:ele}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
          username: root
          password: 12345678
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10
    host: 127.0.0.1
    password: